//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserPathEngraver.UI.Win.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserPathEngraver.UI.Win.Resources.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsTitle {
            get {
                return ResourceManager.GetString("ActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto center view.
        /// </summary>
        public static string AutoCenterViewText {
            get {
                return ResourceManager.GetString("AutoCenterViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelCommandText {
            get {
                return ResourceManager.GetString("CancelCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectButtonText {
            get {
                return ResourceManager.GetString("ConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButtonText {
            get {
                return ResourceManager.GetString("ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomThemeText {
            get {
                return ResourceManager.GetString("CustomThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkThemeText {
            get {
                return ResourceManager.GetString("DarkThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string DeviceStatusConnectingText {
            get {
                return ResourceManager.GetString("DeviceStatusConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string DeviceStatusDisconnectedText {
            get {
                return ResourceManager.GetString("DeviceStatusDisconnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        public static string DeviceStatusDisconnectingText {
            get {
                return ResourceManager.GetString("DeviceStatusDisconnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        public static string DeviceStatusExecutingText {
            get {
                return ResourceManager.GetString("DeviceStatusExecutingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string DeviceStatusReadyText {
            get {
                return ResourceManager.GetString("DeviceStatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        public static string DeviceStatusTitle {
            get {
                return ResourceManager.GetString("DeviceStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DisconnectButtonText {
            get {
                return ResourceManager.GetString("DisconnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show halo.
        /// </summary>
        public static string EnableVisualEffectsText {
            get {
                return ResourceManager.GetString("EnableVisualEffectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth [%].
        /// </summary>
        public static string EngravingDurationText {
            get {
                return ResourceManager.GetString("EngravingDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power [%].
        /// </summary>
        public static string EngravingPowerText {
            get {
                return ResourceManager.GetString("EngravingPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraving.
        /// </summary>
        public static string EngravingTitle {
            get {
                return ResourceManager.GetString("EngravingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold [%].
        /// </summary>
        public static string FixedEngravingPowerThresholdText {
            get {
                return ResourceManager.GetString("FixedEngravingPowerThresholdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framing.
        /// </summary>
        public static string FramingCommandText {
            get {
                return ResourceManager.GetString("FramingCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height [cm].
        /// </summary>
        public static string HeightCmText {
            get {
                return ResourceManager.GetString("HeightCmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height [in].
        /// </summary>
        public static string HeightInText {
            get {
                return ResourceManager.GetString("HeightInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height [px].
        /// </summary>
        public static string HeightPxText {
            get {
                return ResourceManager.GetString("HeightPxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///&lt;b&gt;Engrave&lt;/b&gt;
        ///To do this, drag an image file into the window, press &lt;i&gt;Connect&lt;/i&gt;, set your engraving preferences and &lt;i&gt;Start&lt;/i&gt;.
        ///
        ///&lt;b&gt;Settings&lt;/b&gt;
        ///&lt;br /&gt;&lt;i&gt;Depth&lt;/i&gt; sets the duration for which the engraver stays at a position.
        ///Exact duration depends on the device, so it is specified here in percent.
        ///
        ///&lt;i&gt;Variable burn intensity&lt;/i&gt;: If active, the burn intensity is determined by the brightness of the pixel (including alpha channel).
        ///
        ///&lt;i&gt;Max. Power&lt;/i&gt; limits the burn intensity to a maximum [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable burn intensity.
        /// </summary>
        public static string IsPowerVariableText {
            get {
                return ResourceManager.GetString("IsPowerVariableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%h}h {0:%m}m {0:%s}s.
        /// </summary>
        public static string JobElapsedDurationFormatText {
            get {
                return ResourceManager.GetString("JobElapsedDurationFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Elapsed Duration.
        /// </summary>
        public static string JobElapsedDurationTitle {
            get {
                return ResourceManager.GetString("JobElapsedDurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} completed.
        /// </summary>
        public static string JobStatusDoneFormatText {
            get {
                return ResourceManager.GetString("JobStatusDoneFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job active.
        /// </summary>
        public static string JobStatusNoneText {
            get {
                return ResourceManager.GetString("JobStatusNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paused.
        /// </summary>
        public static string JobStatusPausedFormatText {
            get {
                return ResourceManager.GetString("JobStatusPausedFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string JobStatusRunningFormatText {
            get {
                return ResourceManager.GetString("JobStatusRunningFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopped.
        /// </summary>
        public static string JobStatusStoppedFormatText {
            get {
                return ResourceManager.GetString("JobStatusStoppedFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        public static string JobStatusTitle {
            get {
                return ResourceManager.GetString("JobStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightThemeText {
            get {
                return ResourceManager.GetString("LightThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Power [%].
        /// </summary>
        public static string MaximumEngravingPowerText {
            get {
                return ResourceManager.GetString("MaximumEngravingPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseButtonText {
            get {
                return ResourceManager.GetString("PauseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster optimized.
        /// </summary>
        public static string PlottingModeRasterOptimizedText {
            get {
                return ResourceManager.GetString("PlottingModeRasterOptimizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasterized.
        /// </summary>
        public static string PlottingModeRasterText {
            get {
                return ResourceManager.GetString("PlottingModeRasterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string PlottingModeTitle {
            get {
                return ResourceManager.GetString("PlottingModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve aspect ratio.
        /// </summary>
        public static string PreserveAspectRatioText {
            get {
                return ResourceManager.GetString("PreserveAspectRatioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} Updates/s.
        /// </summary>
        public static string RenderRateFormatText {
            get {
                return ResourceManager.GetString("RenderRateFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom [%].
        /// </summary>
        public static string ScaleText {
            get {
                return ResourceManager.GetString("ScaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help.
        /// </summary>
        public static string ShowHelpText {
            get {
                return ResourceManager.GetString("ShowHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraver.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string UnitCmText {
            get {
                return ResourceManager.GetString("UnitCmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string UnitInText {
            get {
                return ResourceManager.GetString("UnitInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string UnitPxText {
            get {
                return ResourceManager.GetString("UnitPxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitText {
            get {
                return ResourceManager.GetString("UnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Rate.
        /// </summary>
        public static string UpdateRateTitle {
            get {
                return ResourceManager.GetString("UpdateRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width [cm].
        /// </summary>
        public static string WidthCmText {
            get {
                return ResourceManager.GetString("WidthCmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width [in].
        /// </summary>
        public static string WidthInText {
            get {
                return ResourceManager.GetString("WidthInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width [px].
        /// </summary>
        public static string WidthPxText {
            get {
                return ResourceManager.GetString("WidthPxText", resourceCulture);
            }
        }
    }
}
