//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserPathEngraver.UI.Win.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserPathEngraver.UI.Win.Resources.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto center view.
        /// </summary>
        public static string AutoCenterViewText {
            get {
                return ResourceManager.GetString("AutoCenterViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show halo.
        /// </summary>
        public static string EnableVisualEffectsText {
            get {
                return ResourceManager.GetString("EnableVisualEffectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth [%].
        /// </summary>
        public static string EngravingDurationText {
            get {
                return ResourceManager.GetString("EngravingDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power [%].
        /// </summary>
        public static string EngravingPowerText {
            get {
                return ResourceManager.GetString("EngravingPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraving.
        /// </summary>
        public static string EngravingTitle {
            get {
                return ResourceManager.GetString("EngravingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold [%].
        /// </summary>
        public static string FixedEngravingPowerThresholdText {
            get {
                return ResourceManager.GetString("FixedEngravingPowerThresholdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height [cm].
        /// </summary>
        public static string HeightCmText {
            get {
                return ResourceManager.GetString("HeightCmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height [px].
        /// </summary>
        public static string HeightPxText {
            get {
                return ResourceManager.GetString("HeightPxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is power variable.
        /// </summary>
        public static string IsPowerVariableText {
            get {
                return ResourceManager.GetString("IsPowerVariableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Power [%].
        /// </summary>
        public static string MaximumEngravingPowerText {
            get {
                return ResourceManager.GetString("MaximumEngravingPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PlottingModePathText {
            get {
                return ResourceManager.GetString("PlottingModePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasterized.
        /// </summary>
        public static string PlottingModeRasterizedText {
            get {
                return ResourceManager.GetString("PlottingModeRasterizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string PlottingModeTitle {
            get {
                return ResourceManager.GetString("PlottingModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve aspect ratio.
        /// </summary>
        public static string PreserveAspectRatioText {
            get {
                return ResourceManager.GetString("PreserveAspectRatioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} Updates/s.
        /// </summary>
        public static string RenderRateFormatText {
            get {
                return ResourceManager.GetString("RenderRateFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom [%].
        /// </summary>
        public static string ScaleText {
            get {
                return ResourceManager.GetString("ScaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help.
        /// </summary>
        public static string ShowHelpText {
            get {
                return ResourceManager.GetString("ShowHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraver.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string UnitCmText {
            get {
                return ResourceManager.GetString("UnitCmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string UnitPxText {
            get {
                return ResourceManager.GetString("UnitPxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitText {
            get {
                return ResourceManager.GetString("UnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width [cm].
        /// </summary>
        public static string WidthCmText {
            get {
                return ResourceManager.GetString("WidthCmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width [px].
        /// </summary>
        public static string WidthPxText {
            get {
                return ResourceManager.GetString("WidthPxText", resourceCulture);
            }
        }
    }
}
